In [ ]:
Создайте массив , состоящий из 10 случайных целых чисел из диапазона от 1 до 20, затем создайте массив состоящий 
из 5 элементов, начиная со 2 по порядку. Выведите значения обоих массивов при помощи функции print()

Создайте массив , состоящий из 10 случайных целых чисел из диапазона от 0 до 20, затем создайте массив состоящий 
из элементов, начиная с третьего по порядку до последнего. Выведите значения обоих массивов при помощи функции print()

Создайте двумерный массив , состоящий из случайных целых чисел из диапазона от 3 до 11, в котором 4 строки и 3 столбца. 
Затем создайте массив состоящий из элементов , второй и третьей строки и первого и второго столбца по порядку. Выведите значения обоих массивов при помощи функции print()

Создайте двумерный массив , состоящий из случайных целых чисел из диапазона от 0 до 9, в котором 4 строки и 6 столбцов. 
Затем создайте массив состоящий из элементов , которые больше числа 3. Выведите значения обоих массивов при помощи функции print()

In [5]:
import numpy as np
rand_arr = np.random.randint(3,12,12).reshape(4,3)

In [10]:
rand_arr


array([[ 9, 10,  3],
       [ 7,  9, 10],
       [ 6,  6,  6],
       [11,  8,  3]])

In [11]:
rand_arr[1:3,:2]

array([[7, 9],
       [6, 6]])

In [16]:
rand_arr2 = np.random.randint(0, 10, 24).reshape(4, 6)
rand_arr2

array([[8, 1, 6, 2, 6, 4],
       [8, 3, 0, 4, 3, 0],
       [3, 6, 1, 4, 3, 2],
       [8, 2, 2, 3, 0, 4]])

In [17]:
rand_arr2[rand_arr2 > 3]

array([8, 6, 6, 4, 8, 4, 6, 4, 8, 4])