In [ ]:
Создайте массив , состоящий из 10 случайных целых чисел из диапазона от 1 до 20, 
затем создайте массив состоящий из 10 элементов, начиная с 2. Выведите значения этих массивов, 
а также их сумму, при помощи функции print()

Создайте массив , состоящий из 7 случайных целых чисел из диапазона от 0 до 9, затем создайте 
новый массив состоящий из 7 элементов первого массива, увеличенных в 3 раза. Выведите значения этих массивов 
при помощи функции print()

Создайте массив состоящий из квадратных корней 20 элементов по порядку, начиная с 7. Выведите значение массива 
при помощи функции print()

In [2]:
import numpy as np
arr1 = np.random.randint(1,21,10)
arr1

array([12, 13, 11,  9, 18,  7,  7,  9, 10,  7])

In [3]:
arr2 = np.random.randint(2,21,10)
arr2

array([ 8,  3,  2, 17, 16,  7,  5, 12, 14, 20])

In [4]:
arr1+arr2

array([20, 16, 13, 26, 34, 14, 12, 21, 24, 27])

In [6]:


rand_array = np.random.randint(0, 10, 7)
rand_array

array([1, 1, 3, 6, 5, 6, 6])

In [8]:
rand2_array = rand_array * 3
rand2_array

array([ 3,  3,  9, 18, 15, 18, 18])

In [9]:
np_array = np.linspace(7,26, 20)
np_array

array([ 7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18., 19.,
       20., 21., 22., 23., 24., 25., 26.])

In [14]:
np2_array = np.sqrt(np_array)
np2_array

array([2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
       3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ,
       4.12310563, 4.24264069, 4.35889894, 4.47213595, 4.58257569,
       4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951])